<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>RefinedGem</AssemblyName>
    <RootNamespace>RefinedGem</RootNamespace>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildThisFileDirectory)build\dll\</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <Sts2DataDir Condition="'$(Sts2DataDir)' == ''">D:\citrus_steam_games\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64</Sts2DataDir>
    <RitsuLibDir Condition="'$(RitsuLibDir)' == ''">D:\citrus_steam_games\steamapps\workshop\content\2868840\3747602295\lib\0.111.0</RitsuLibDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(Sts2DataDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>$(Sts2DataDir)\GodotSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="STS2-RitsuLib">
      <HintPath>$(RitsuLibDir)\STS2-RitsuLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="locales\**\*.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tools\**" />
  </ItemGroup>
</Project>
